sudo: required
install:
  - npm install -g elm@0.18
  - elm-package install -y
script:
  - make release
  - echo elm-stuff > .gitignore

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
